/* Discord Event Poster v0.1.0 - no external runtime dependencies. */
(function () {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const STORE = "discord-event-poster.webhook";
  const state = { events: [], posting: false };
  const today = new Date();

  function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
  function parseWebhook(raw) {
    try { const u = new URL(raw.trim()); if (!/^https?:$/.test(u.protocol) || !/^(discord\.com|discordapp\.com|canary\.discord\.com|ptb\.discord\.com)$/.test(u.hostname) || !/^\/api\/webhooks\/[^/]+\/[^/]+$/.test(u.pathname)) return null; return u; } catch { return null; }
  }
  function splitEvents(text) { const re = /【([^】\n]{1,40})】\s*[『「“"]([^』」”"]+)[』」”"]/g; const starts = []; let m; while ((m = re.exec(text))) starts.push({ index:m.index, region:m[1].trim(), title:m[2].trim(), end:re.lastIndex }); if (!starts.length) return { events:[], warnings:["イベント開始形式（【地域】『タイトル』）を認識できませんでした。"] }; const events = starts.map((s, i) => ({ raw:text.slice(s.index, i + 1 < starts.length ? starts[i + 1].index : text.length).trim(), region:s.region, title:s.title })); const prefix = text.slice(0, starts[0].index).trim(); return { events, warnings:prefix ? [`先頭にイベントとして認識できない文章があります（${prefix.length}文字）。`] : [] }; }
  function extractLinks(raw) { const links = []; const md = /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g; let m; while ((m = md.exec(raw))) links.push({ label:m[1], url:m[2] }); const plain = raw.match(/https?:\/\/[^\s)]+/g) || []; plain.forEach((url) => { if (!links.some((x) => x.url === url)) links.push({ label:url, url }); }); return links.filter((x) => !/^(https?:\/\/t\.co|https?:\/\/[^/]+\/(?:hashtag|emoji)\b)/i.test(x.url)); }
  function datePart(raw) { const m = raw.match(/(?:^|[\s\n])((?:\d{4}[年\/-])?\d{1,2})[月\/-](\d{1,2})(?:日)?/); return m ? { month:m[1].replace(/^\d{4}[年\/-]/, ""), day:m[2], explicitYear:/^\d{4}/.test(m[1]) } : null; }
  function parsePeriod(raw) { const match = raw.match(/(\d{1,2})\s*[月\/]\s*(\d{1,2})(?:日)?\s*(?:〜|～|-|~)\s*(?:(\d{1,2})\s*[月\/]\s*)?(\d{1,2})?(?:日)?/); const opening = raw.match(/(\d{1,2})\s*[月\/]\s*(\d{1,2})(?:日)?\s*(?:開幕|スタート)/); const onlyEnd = raw.match(/〜\s*(\d{1,2})\s*[月\/]\s*(\d{1,2})/); if (match) { const sm=match[1], sd=match[2], em=match[3] || sm, ed=match[4]; const startYear=today.getFullYear(), endYear=(Number(em)<Number(sm)?startYear+1:startYear); return { start:`${startYear}/${sm}/${sd}`, end:`${endYear}/${em}/${ed || ""}`, warning:!match[4]?"終了日が不明です。":(!match[3]&&Number(ed)<Number(sd)?"年またぎの可能性があります。":"") }; } if (opening) return { start:`${today.getFullYear()}/${opening[1]}/${opening[2]}`, end:"", warning:"「開幕」表記から開始日のみ抽出しました。年は推定です。" }; if (onlyEnd) return { start:"", end:`${today.getFullYear()}/${onlyEnd[1]}/${onlyEnd[2]}`, warning:"開始日が不明です。" }; const relative = raw.match(/(明日|明後日)開幕/); if (relative) { const d=new Date(today); d.setDate(d.getDate()+(relative[1]==="明日"?1:2)); return { start:d.toISOString().slice(0,10).replaceAll("-","/"), end:"", warning:`「${relative[1]}」を解析基準日から推定しました。` }; } return { start:"", end:"", warning:"開催期間を抽出できませんでした。" }; }
  function analyze(raw, index) { const links=extractLinks(raw); const p=parsePeriod(raw); const tags=(raw.match(/#[^\s#]+/g)||[]).join(" "); const desc=raw.replace(/^【[^】]+】\s*[『「“"][^』」”"]+[』」”"]\s*/,"" ).replace(/\[[^\]]+\]\([^)]*\)|https?:\/\/[^\s)]+/g," ").replace(/#[^\s#]+/g," ").trim(); return { id:`event-${index+1}`, selected:true, status:"未送信", region:"", title:"", start:p.start,end:p.end,description:desc, url:links[0]?.url||"", tags, raw, warnings:p.warning?[p.warning]:[], candidates:links.map((x)=>x.url), duplicate:false, ...{ region:raw.match(/^【([^】]+)】/)?.[1]?.trim()||"", title:raw.match(/^【[^】]+】\s*[『「“"]([^』」”"]+)[』」”"]/)?.[1]?.trim()||"" } }; }
  function runAnalysis(text) { const split=splitEvents(text); const events=split.events.map((x,i)=>analyze(x.raw,i)); const seen=new Map(); events.forEach((e)=>{ const key=`${e.region}|${e.title}`; e.duplicate=seen.has(key); seen.set(key,true); if(e.duplicate)e.warnings.push("同じ入力内に同じ地域・タイトルがあります。"); }); return { events, warnings:split.warnings }; }
  function contentFor(e) { const period=e.start||e.end?`${e.start||"不明"}〜${e.end||""}`:"不明"; return `📍 **開催地域：${e.region||"不明"}**\n\n📅 **開催期間：${period}**\n\n${e.description||""}\n\n${e.url?`🔗 **公式サイト**\n${e.url}\n\n`:""}${e.tags||""}`.trim(); }
  function threadName(e) { return `【${e.region||"不明"}】${e.title}`; }
  function validateEvent(e) { const errors=[]; if(!e.title)errors.push("タイトルがありません"); if(threadName(e).length>100)errors.push("スレッド名が100文字を超えています"); if(contentFor(e).length>2000)errors.push("本文が2000文字を超えています"); if(e.url){try{const u=new URL(e.url);if(!/^https?:$/.test(u.protocol))errors.push("公式URLはhttp/httpsのみです")}catch{errors.push("公式URLが不正です")}} return errors; }
  function renderCards() { $("count").textContent=`${state.events.length}件`; $("cards").innerHTML=state.events.map((e,i)=>`<article class="card ${e.selected?"selected":""} ${e.duplicate?"duplicate":""}" data-id="${e.id}"><div class="card-top"><input class="select-event" type="checkbox" ${e.selected?"checked":""} aria-label="${escapeHtml(e.title)}を投稿対象にする"><div><h3>${escapeHtml(e.title||"無題のイベント")}</h3><p class="hint">元文 ${e.raw.length}文字・状態：${e.status}</p></div></div><div class="card-grid"><label>地域<input data-field="region" value="${escapeHtml(e.region)}"></label><label>タイトル<input data-field="title" value="${escapeHtml(e.title)}"></label><label>開始日<input data-field="start" value="${escapeHtml(e.start)}" placeholder="2026/10/23"></label><label>終了日<input data-field="end" value="${escapeHtml(e.end)}" placeholder="2027/01/17"></label><label>公式URL<input data-field="url" value="${escapeHtml(e.url)}" placeholder="https://..."></label><label>ハッシュタグ<input data-field="tags" value="${escapeHtml(e.tags)}"></label><label style="grid-column:1/-1">説明<textarea data-field="description">${escapeHtml(e.description)}</textarea></label></div>${e.warnings.length?`<p class="warning">⚠ ${e.warnings.map(escapeHtml).join(" / ")}</p>`:""}</article>`).join(""); $("selected-count").textContent=`投稿予定 ${state.events.filter(e=>e.selected).length}件`; $("review").disabled=!state.events.some(e=>e.selected); }
  function renderPreview() { const selected=state.events.filter(e=>e.selected); $("preview").innerHTML=selected.map((e)=>`<article><strong>${escapeHtml(threadName(e))}</strong><br><br>${escapeHtml(contentFor(e))}</article>`).join(""); }
  function saveUrl() { const u=parseWebhook($("webhook").value); if($("remember").checked&&u)localStorage.setItem(STORE,u.href); else localStorage.removeItem(STORE); }
  async function postOne(e) { const url=parseWebhook($("webhook").value); const response=await fetch(`${url.href}?wait=true`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:contentFor(e),thread_name:threadName(e),allowed_mentions:{parse:[]}})}); if(response.status===429){let wait=Number(response.headers.get("Retry-After"))||0;try{const body=await response.json();wait=Number(body.retry_after)||wait}catch{} const err=new Error(`レート制限。${Math.ceil(wait)}秒待ってください。`);err.rate=true;throw err} if(!response.ok){let msg=`HTTP ${response.status}`;try{const body=await response.json();if(body.message)msg+=`：${body.message}`}catch{} throw new Error(msg)} let body=null;try{body=await response.json()}catch{} return body; }
  async function postSelected() { if(state.posting)return; const url=parseWebhook($("webhook").value); if(!url){alert("Webhook URLを確認してください。");return} const selected=state.events.filter(e=>e.selected); const invalid=selected.flatMap((e)=>validateEvent(e).map((x)=>`${e.title}: ${x}`)); if(invalid.length){alert(`投稿できないイベントがあります。\n\n${invalid.join("\n")}`);return} if(!confirm(`${selected.length}件をDiscordへ投稿します。よろしいですか？`))return; state.posting=true; $("post").disabled=true; $("status-panel").classList.remove("hidden"); const results=[]; for(const e of selected){e.status="送信中"; try{const body=await postOne(e);e.status="成功";results.push({e,ok:true,body})}catch(error){e.status=error.rate?"結果不明":"失敗";results.push({e,ok:false,error})}} state.posting=false; $("post").disabled=false; renderResults(results); }
  function renderResults(results) { const ok=results.filter(x=>x.ok).length; $("result-summary").textContent=`${ok}/${results.length}件が成功しました。`; $("post-results").innerHTML=results.map(({e,ok,body,error})=>`<div class="result ${ok?"ok":"error"}"><strong>${ok?"成功":"失敗・"+e.status}：</strong>${escapeHtml(e.title)}${ok&&body?.id?` <small>メッセージID ${escapeHtml(body.id)}</small>`:`<br><small>${escapeHtml(error?.message||"")}</small>`}</div>`).join(""); const failed=results.filter(x=>!x.ok).map(x=>x.e); $("retry-failed").classList.toggle("hidden",!failed.length); $("retry-failed").onclick=()=>{failed.forEach(e=>e.selected=true);postSelected()}; }
  $("toggle-secret").onclick=()=>{const input=$("webhook");input.type=input.type==="password"?"text":"password";$("toggle-secret").textContent=input.type==="password"?"表示":"隠す"}; $("remember").onchange=saveUrl; $("forget").onclick=()=>{localStorage.removeItem(STORE);$("webhook").value="";$("remember").checked=false}; $("parse").onclick=()=>{const result=runAnalysis($("source").value);state.events=result.events;if(!state.events.length){$("input-status").textContent=result.warnings.join(" ");return}$("results-panel").classList.remove("hidden");$("confirm-panel").classList.add("hidden");renderCards();$("input-status").textContent=result.warnings.join(" ")||`${state.events.length}件を認識しました。`}; $("cards").addEventListener("change",(ev)=>{const card=ev.target.closest(".card");if(!card)return;const e=state.events.find(x=>x.id===card.dataset.id);if(ev.target.classList.contains("select-event"))e.selected=ev.target.checked;else if(ev.target.dataset.field)e[ev.target.dataset.field]=ev.target.value;card.classList.toggle("selected",e.selected);$("selected-count").textContent=`投稿予定 ${state.events.filter(x=>x.selected).length}件`;$("review").disabled=!state.events.some(x=>x.selected)}); $("cards").addEventListener("input",(ev)=>{const card=ev.target.closest(".card"),e=state.events.find(x=>x.id===card?.dataset.id);if(e&&ev.target.dataset.field)e[ev.target.dataset.field]=ev.target.value}); $("select-all").onclick=()=>{state.events.forEach(e=>e.selected=true);renderCards()};$("clear-all").onclick=()=>{state.events.forEach(e=>e.selected=false);renderCards()};$("review").onclick=()=>{renderPreview();$("confirm-panel").classList.remove("hidden");window.scrollTo({top:$('confirm-panel').offsetTop-20,behavior:"smooth"})};$("back").onclick=()=>$("confirm-panel").classList.add("hidden");$("post").onclick=postSelected;
  const stored=localStorage.getItem(STORE);if(stored&&parseWebhook(stored)){$("webhook").value=stored;$("remember").checked=true}
  window.EventPoster={splitEvents,extractLinks,parsePeriod,runAnalysis,contentFor,validateEvent,parseWebhook};
}());
