const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('app.js', 'utf8');
const elements = new Proxy({}, { get: (target, key) => key === 'addEventListener' ? () => {} : key === 'classList' ? {add(){},remove(){},toggle(){}} : key === 'offsetTop' ? 0 : key === 'value' ? '' : undefined });
const context = { document:{getElementById:()=>elements}, window:{scrollTo(){}}, localStorage:{getItem:()=>null,setItem(){},removeItem(){}}, sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}}, TextEncoder,crypto:require('node:crypto').webcrypto,URL, fetch:async()=>({}), alert(){}, confirm:()=>true, console, setTimeout,clearTimeout };
vm.createContext(context);vm.runInContext(fs.readFileSync('poster-client.js','utf8'),context); vm.runInContext(source, context);
const E = context.window.EventPoster;
function assert(ok, msg){ if(!ok) throw new Error(msg); }
const sample = '【東京】『埋もれゆく部屋からの脱出』 10/9〜11/29 説明 [公式](https://example.com) #脱出\n【埼玉】『ウワサバナシ調査委員会 case2「言祝ぎの家-呪われた花嫁-」』 11/7〜8';
const result = E.runAnalysis(sample);
assert(result.events.length === 2, '複数イベント');
assert(result.events[1].title.includes('言祝ぎの家'), 'タイトル内引用符');
assert(result.events[0].url === 'https://example.com', 'Markdownリンク');
assert(E.runAnalysis('改行なしの説明').events.length === 0, '解析不能警告');
assert(E.validateEvent({region:'東京',title:'x'.repeat(101),start:'',end:'',description:'',url:'',tags:''}).length, 'スレッド名制限');
assert(E.MAX_TAGS === 5, '最大5タグ');
assert(E.autoTagEvent({title:'脱出',description:'ホラー',raw:'脱出 ホラー',warnings:[]}).includes('謎解き'), 'タグ自動判定');
assert(E.appliedTagsFor({selectedTags:['謎解き']})[0].id === '', '未設定タグIDは空');
assert(E.runAnalysis(Array.from({length:6},(_,i)=>`【東京】『イベント${i}』説明`).join('\n')).events.length===6, 'イベント件数を切り捨てない');
assert(E.validateEvent({title:'題',selectedTags:Array(6).fill('ホラー')}).some(x=>x.includes('5件')), '5タグ上限');
const edited={title:'普通の催し',description:'説明',raw:'ホラー',warnings:[]};
assert(E.autoTagEvent(edited).length===0, '編集済みタイトル本文だけ判定');
console.log('PASS: current parser, links, warnings, limits, manual/automatic tags');
