'use strict';
globalThis.fetch=()=>{throw new Error('NETWORK_FORBIDDEN_IN_UNIT_TEST');};
const {test}=require('node:test'),assert=require('node:assert/strict');
const candidate=require('../tools/wrangler-strict-candidate.cjs');
const {source}=candidate.original(),patched=candidate.patch(source);
// Expose real bundled functions only in the isolated test module; no API traffic.
const expose=`
init_config_diffs();init_map_worker_metadata_bindings();init_create_worker_upload_form();init_durable();init_deploy_confirm();
exports.auditDiff=getRemoteConfigDiff;exports.auditMap=mapWorkerMetadataBindings;exports.auditForm=createWorkerUploadForm;exports.auditConfirm=getDeployConfirmFunction;
exports.auditMigrations=async(tag)=>{const prior=fetchResult;fetchResult=async()=>({default_environment:{script:{migration_tag:tag}}});try{return await getMigrationsToUpload('discord-event-poster-api',{accountId:'TEST_ACCOUNT',config:{migrations:[{tag:'auth-v1',new_sqlite_classes:['AuthState']}]}});}finally{fetchResult=prior;}};
`;
const before=candidate.load(source,expose),after=candidate.load(patched,expose);
const binding={name:'AUTH_STATE',class_name:'AuthState'},raw={...binding,type:'durable_object_namespace',namespace_id:'5157fbc20842458f8e8269b821e51f47'};
const local={name:'discord-event-poster-api',durable_objects:{bindings:[binding]},observability:{enabled:false}};
const diff=(api,b=raw,l=local)=>api.auditDiff(api.auditMap([b]),l);
test('exact one insertion; base pinned; all other Wrangler bytes unchanged',()=>{assert.equal(patched.replace(candidate.INSERT,''),source);assert.throws(()=>candidate.patch(source+' '));assert.equal(candidate.sha(source),candidate.ORIGINAL_SHA);});
test('original reproduces empty false conflict; candidate removes only undefined fields',()=>{assert.equal(diff(before).nonDestructive,false);assert.equal(diff(after).diff,null);const metadata=after.auditMap([raw]);assert.ok(Object.hasOwn(metadata.durable_objects.bindings[0],'script_name'));assert.ok(Object.hasOwn(metadata.durable_objects.bindings[0],'environment'));});
test('comparison does not mutate remote or local bindings',()=>{const remote=after.auditMap([raw]),saved=structuredClone(remote),l=structuredClone(local);after.auditDiff(remote,l);assert.deepEqual(remote,saved);assert.deepEqual(l,local);});
test('real existing binding name/class/script/environment changes still rejected',()=>{for(const [field,value]of [['name','OTHER'],['class_name','OtherState'],['script_name','other-worker'],['environment','other-environment'],['environment',null],['environment',''],['environment',false],['environment',0]])assert.equal(diff(after,{...raw,[field]:value}).nonDestructive,false,field+String(value));assert.equal(after.auditDiff(after.auditMap([raw]),{...local,durable_objects:{bindings:[]}}).nonDestructive,false);});
test('explicit equal optional values remain equal and actual value differences remain visible',()=>{const r={...raw,script_name:'other-worker',environment:'production'},l={...local,durable_objects:{bindings:[{...binding,script_name:'other-worker',environment:'production'}]}};assert.equal(diff(after,r,l).diff,null);assert.equal(diff(after,{...r,environment:'staging'},l).nonDestructive,false);});
test('different non-DO binding and observability differences remain destructive',()=>{assert.equal(after.auditDiff({services:[{binding:'SERVICE',service:'old'}]},{...local,services:[{binding:'SERVICE',service:'new'}]}).nonDestructive,false);assert.equal(after.auditDiff({...after.auditMap([raw]),observability:{enabled:true}},local).nonDestructive,false);});
test('namespace ID is not compared: independent preservation gate remains required',()=>{assert.equal(diff(after,{...raw,namespace_id:'11111111111111111111111111111111'}).diff,null);});
test('real strict confirm still refuses continuation in CI without upload',async()=>{const previous=process.env.CI,exitCode=process.exitCode;process.env.CI='true';try{assert.equal(await after.auditConfirm({strictMode:true})('TEST_ONLY'),false);}finally{process.exitCode=exitCode;if(previous===undefined)delete process.env.CI;else process.env.CI=previous;}});
test('auth-v1 generates no migration for original and candidate using mock metadata GET',async()=>{assert.equal(await before.auditMigrations('auth-v1'),undefined);assert.equal(await after.auditMigrations('auth-v1'),undefined);assert.deepEqual(await before.auditMigrations(undefined),await after.auditMigrations(undefined));});
test('upload metadata, keep vars/secrets and DO target are byte-equivalent',()=>{
 const worker={main:{name:'index.mjs',type:'esm',content:'export default {}'},modules:[],compatibility_date:'2026-04-01',compatibility_flags:[],keepVars:true,keepSecrets:true};
 const bindings={AUTH_STATE:{type:'durable_object_namespace',class_name:'AuthState'},FORUM_POSTS_ENABLED:{type:'plain_text',value:'false'},TEST_SECRET:{type:'secret_text',value:'TEST_ONLY_NOT_PRODUCTION'}};
 const a=before.auditForm(worker,bindings,{dryRun:true}).get('metadata'),b=after.auditForm(worker,bindings,{dryRun:true}).get('metadata');assert.equal(a,b);const metadata=JSON.parse(b);assert.ok(metadata.bindings.some(x=>x.type==='durable_object_namespace'&&x.name==='AUTH_STATE'&&x.class_name==='AuthState'));assert.equal(metadata.migrations,undefined);assert.deepEqual(metadata.keep_bindings,['plain_text','json','secret_text','secret_key']);assert.ok(metadata.bindings.some(x=>x.name==='FORUM_POSTS_ENABLED'&&x.text==='false'));assert.ok(metadata.bindings.some(x=>x.name==='TEST_SECRET'&&x.type==='secret_text'));
});
const args=['deploy','--dry-run','--strict','--keep-vars','--config','worker/work/wrangler-strict-validation/wrangler.jsonc','--outdir','worker/work/wrangler-strict-validation/candidate-bundle','--var','FORUM_POSTS_ENABLED:false'];
test('validation-only CLI rejects actual deploy, strict bypass, credential files and argument overrides',()=>{candidate.validateArguments(args);for(const bad of [args.filter(x=>x!=='--dry-run'),args.filter(x=>x!=='--strict'),[...args,'--dry-run=false'],[...args,'--strict=false'],[...args,'--secrets-file','secrets.json'],['secret','put','TEST'],args.map(x=>x==='FORUM_POSTS_ENABLED:false'?'FORUM_POSTS_ENABLED:true':x),args.map(x=>x==='worker/work/wrangler-strict-validation/wrangler.jsonc'?'worker/wrangler.jsonc':x)])assert.throws(()=>candidate.validateArguments(bad));});
test('actual candidate process rejects non-dry-run before loading the CLI',()=>{const {spawnSync}=require('node:child_process'),path=require('node:path');const result=spawnSync(process.execPath,[path.resolve(__dirname,'../tools/wrangler-strict-candidate.cjs'),...args.filter(x=>x!=='--dry-run')],{encoding:'utf8'});assert.equal(result.status,1);assert.equal(result.stdout,'');assert.match(result.stderr,/CANDIDATE_VALIDATION_FAILED_OR_COMMAND_REJECTED/);assert.ok(!result.stderr.includes('Validation candidate:'));});
