'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
globalThis.fetch=()=>{throw new Error('REAL_NETWORK_FORBIDDEN');};
const d=require('../tools/wrangler-stage1-diff.cjs'),s=require('../tools/wrangler-stage1-deploy.cjs');
const account='a'.repeat(32),root='/accounts/'+account,service=root+'/workers/services/'+s.WORKER,script=root+'/workers/scripts/'+s.WORKER;
test('account argument constrained and no deployment flags accepted',()=>{assert.equal(d.parse(['--account-id',account]),account);for(const a of [[],['--execute'],['--account-id',account,'--strict=false'],['--account-id','INVALID']])assert.throws(()=>d.parse(a));});
test('no diff and strict undefined assets only are diagnostic PASS',()=>{assert.equal(d.describe(null).classification,'NO_DIFF');assert.deepEqual(d.describe({assets__added:undefined}),{status:'PASS',classification:'ONLY_UNDEFINED_ASSETS',entries:[{key:'assets__added',present:true,type:'undefined'}]});});
test('real assets, multiple and unknown differences fail without values',()=>{for(const diff of [{assets__added:{directory:'DO_NOT_PRINT'}},{assets__added:null},{assets__added:undefined,unknown__added:undefined},{unknown__added:'DO_NOT_PRINT'},{}]){const r=d.describe(diff);assert.equal(r.status,'FAIL');assert.ok(!JSON.stringify(r).includes('DO_NOT_PRINT'));}assert.throws(()=>d.describe({'https://private/token':true}));});
test('transport permits only fixed GET and refuses every write and redirect without retry',async()=>{
 let calls=0;const read=d.reader(account,{apiToken:'TEST_ONLY'},async(_url,init)=>{calls++;assert.equal(init.method,'GET');assert.equal(init.redirect,'manual');return {ok:true,json:async()=>({success:true,result:{}})};});await read(root);for(const init of [{method:'POST'},{method:'PUT'},{method:'DELETE'},{method:'GET',body:'x'}])await assert.rejects(()=>read(root,init));await assert.rejects(()=>read(root+'/secrets'));assert.equal(calls,1);
 const redirect=d.reader(account,{apiToken:'TEST_ONLY'},async()=>{calls++;return {ok:false,status:302};});await assert.rejects(()=>redirect(root));assert.equal(calls,2);
});
test('auth and retrieval failures stop without retry or exception exposure',async()=>{let calls=0;const fetch=async()=>{calls++;return {ok:false,status:401};};await assert.rejects(()=>d.reader(account,undefined,fetch)(root));assert.equal(calls,0);await assert.rejects(()=>d.reader(account,{apiToken:'TEST_ONLY'},fetch)(root));assert.equal(calls,1);});
test('transport reason codes are fixed and never include credentials, account, body or exception',async()=>{
 const cases=[[undefined,async()=>{},'authentication','CREDENTIALS_UNAVAILABLE'],[{apiToken:'SECRET_TEST'},async()=>{throw new Error('SECRET_TEST '+account)},'transport','NETWORK_OR_TIMEOUT'],[{apiToken:'SECRET_TEST'},async()=>({ok:false,status:403}),'transport','AUTHORIZATION_REJECTED'],[{apiToken:'SECRET_TEST'},async()=>({ok:false,status:302}),'transport','REDIRECT_REJECTED'],[{apiToken:'SECRET_TEST'},async()=>({ok:false,status:500}),'transport','HTTP_REJECTED'],[{apiToken:'SECRET_TEST'},async()=>({ok:true,json:async()=>{throw new Error('SECRET_TEST')}}),'response','INVALID_JSON'],[{apiToken:'SECRET_TEST'},async()=>({ok:true,json:async()=>({success:false,errors:['SECRET_TEST']})}),'response','API_RESULT_REJECTED']];
 for(const [auth,fetcher,phase,reason]of cases)await assert.rejects(()=>d.reader(account,auth,fetcher)(root),error=>{const r=d.failure(error,'diagnosis');assert.equal(r.phase,phase);assert.equal(r.reason,reason);assert.equal(r.endpoint,'ACCOUNT');assert.ok(!JSON.stringify(r).includes('SECRET_TEST'));assert.ok(!JSON.stringify(r).includes(account));return true;});
 assert.deepEqual(d.failure(new Error('SECRET_TEST'),'comparison'),{status:'FAIL',phase:'comparison',reason:'STAGE_FAILED'});
});
test('diagnosis locates preflight, local config, remote config, comparison and final preflight failures',async()=>{
 for(const phase of ['preflight','local_config','remote_config','comparison','final_preflight']){
  const f=fixture();let accountReads=0;const read=async p=>{if(p===root&&++accountReads===(phase==='preflight'?1:phase==='final_preflight'?2:-1))throw new Error('SECRET_TEST');return structuredClone(f[p]);};
  const api={diffReadConfig:()=>{if(phase==='local_config')throw new Error('SECRET_TEST');return {};},diffRemote:async()=>{if(phase==='remote_config')throw new Error('SECRET_TEST');return {};},diffCompare:()=>{if(phase==='comparison')throw new Error('SECRET_TEST');return {diff:null};}};
  await assert.rejects(()=>d.diagnose(account,api,read),error=>{assert.deepEqual(d.failure(error,'unknown'),{status:'FAIL',phase,reason:'STAGE_FAILED'});return true;});
 }
});
const fixture=()=>({[root]:{id:account},[script+'/versions']:{items:[{id:s.VERSION}]},[script+'/deployments']:{deployments:[{id:'DEPLOYMENT',versions:[{version_id:s.VERSION,percentage:100}]}]},[service]:{default_environment:{environment:'production'}},[service+'/environments/production']:{script:{compatibility_date:'2026-04-01',migration_tag:'auth-v1',has_assets:false,has_modules:true}},[service+'/environments/production/bindings']:[...s.SECRET_NAMES.map(name=>({name,type:'secret_text'})),{name:'AUTH_STATE',type:'durable_object_namespace',class_name:'AuthState',namespace_id:s.NAMESPACE}],[service+'/environments/production/routes?show_zonename=true']:[],[root+'/workers/domains/records?page=0&per_page=5&service='+s.WORKER+'&environment=production']:[],[service+'/environments/production/subdomain']:{enabled:true,previews_enabled:false},[script+'/schedules']:{schedules:[]},[root+'/workers/durable_objects/namespaces?page=1&per_page=100']:[{id:s.NAMESPACE,script:s.WORKER,class:'AuthState',use_sqlite:true}]});
test('actual pinned comparison path reproduces undefined assets; no remote writes',async()=>{
 const f=fixture(),seen=[];const read=async(p,init={})=>{assert.ok(init.method===undefined||init.method==='GET');assert.ok(Object.hasOwn(f,p));seen.push(p);return structuredClone(f[p]);};const api=d.engine(read);const r=await d.diagnose(account,api,read);assert.equal(r.classification,'NO_DIFF');assert.deepEqual(r.entries,[]);assert.ok(!JSON.stringify(r).includes(account));assert.ok(seen.length>10);
 const local=api.diffReadConfig({config:require('node:path').resolve(__dirname,'../wrangler.jsonc')});const remote=await api.diffRemote(s.WORKER,'production','src/index.mjs',account);delete local.assets;assert.equal(d.describe(api.diffCompare(remote,{...local,routes:[]}).diff).classification,'NO_DIFF');
});
test('unknown remote metadata and changed active deployment remain fail closed',async()=>{for(const alter of [f=>f[service+'/environments/production'].script.unknown_setting=true,f=>f[script+'/deployments'].deployments[0].versions[0].percentage=99]){const f=fixture();alter(f);const read=async p=>structuredClone(f[p]),api=d.engine(read);await assert.rejects(()=>d.diagnose(account,api,read));}});
test('auth classification and expiry expose fixed identifiers only',()=>{
 const token='DO_NOT_PRINT',now=Date.parse('2026-10-10T00:00:00Z'),auth={apiToken:token};
 assert.deepEqual(d.authState(auth,auth,undefined,now),{authMethod:'API_TOKEN',oauthExpiry:'UNKNOWN'});
 for(const [expiry,expected]of [['2026-10-09T00:00:00Z','EXPIRED'],['2026-10-11T00:00:00Z','VALID'],['invalid','UNKNOWN'],[undefined,'UNKNOWN']])assert.deepEqual(d.authState(auth,undefined,{oauth_token:token,expiration_time:expiry},now),{authMethod:'OAUTH_CACHE',oauthExpiry:expected});
 assert.equal(d.authState(auth,undefined,{},now).authMethod,'UNKNOWN');assert.equal(d.authState(undefined,{authKey:token,authEmail:token},undefined,now).authMethod,'GLOBAL_KEY');
 assert.ok(!JSON.stringify(d.authState(auth,undefined,{oauth_token:token},now)).includes(token));
});
test('401 and 403 retain fixed endpoint labels for every permitted API',async()=>{
 const paths=[root,service,script+'/versions',script+'/deployments',script+'/schedules',root+'/workers/durable_objects/namespaces?page=1&per_page=100',service+'/environments/production',service+'/environments/production/bindings',service+'/environments/production/routes?show_zonename=true',service+'/environments/production/subdomain',root+'/workers/domains/records?page=0&per_page=5&service='+s.WORKER+'&environment=production'];
 const labels=['ACCOUNT','SERVICE','VERSIONS','DEPLOYMENTS','SCHEDULES','DO_NAMESPACES','ENVIRONMENT','BINDINGS','ROUTES','SUBDOMAIN','DOMAINS'];
 for(const status of [401,403])for(let i=0;i<paths.length;i++){let calls=0;await assert.rejects(()=>d.reader(account,{apiToken:'DO_NOT_PRINT'},async()=>{calls++;return {ok:false,status};})(paths[i]),error=>{assert.deepEqual(d.failure(error,'transport'),{status:'FAIL',phase:'transport',reason:'AUTHORIZATION_REJECTED',endpoint:labels[i],httpStatus:status});return true;});assert.equal(calls,1);}
});
test('credential bridge has only read-only cache access and no refresh invocation',()=>{const api=d.engine();assert.equal(typeof api.diffCache,'function');assert.equal(typeof api.diffEnvAuth,'function');const src=require('node:fs').readFileSync(require.resolve('../tools/wrangler-stage1-diff.cjs'),'utf8');assert.ok(!src.includes('loginOrRefreshIfRequired('));assert.ok(!src.includes('writeAuthCredentials('));});
