'use strict';
globalThis.fetch=()=>{throw new Error('NETWORK_FORBIDDEN');};
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const deploy=require('../tools/wrangler-stage1-deploy.cjs'),candidate=require('../tools/wrangler-strict-candidate.cjs');
const ACCOUNT='a'.repeat(32),root='/accounts/'+ACCOUNT,service=root+'/workers/services/'+deploy.WORKER,script=root+'/workers/scripts/'+deploy.WORKER;
const fixture=()=>({
 [root]:{id:ACCOUNT},[script+'/versions']:{items:[{id:deploy.VERSION}]},[script+'/deployments']:{deployments:[{id:'DEPLOYMENT',versions:[{version_id:deploy.VERSION,percentage:100}]}]},
 [service]:{default_environment:{environment:'production'}},[service+'/environments/production']:{script:{compatibility_date:'2026-04-01',migration_tag:'auth-v1',observability:{enabled:false}}},
 [service+'/environments/production/bindings']:[...deploy.SECRET_NAMES.map(name=>({name,type:'secret_text'})),{name:'AUTH_STATE',type:'durable_object_namespace',class_name:'AuthState',namespace_id:deploy.NAMESPACE}],
 [service+'/environments/production/routes?show_zonename=true']:[],[root+'/workers/domains/records?page=0&per_page=5&service='+deploy.WORKER+'&environment=production']:[],[service+'/environments/production/subdomain']:{enabled:true,previews_enabled:false},[script+'/schedules']:{schedules:[]},
 [root+'/workers/durable_objects/namespaces?page=1&per_page=100']:[{id:deploy.NAMESPACE,script:deploy.WORKER,class:'AuthState',use_sqlite:true}]
});
const reader=f=>async resource=>{if(!Object.hasOwn(f,resource))throw new Error('UNEXPECTED_READ');return structuredClone(f[resource]);};
const metadata=()=>({compatibility_date:'2026-04-01',bindings:[...deploy.SECRET_NAMES.map(name=>({name,type:'inherit'})),{name:'FORUM_POSTS_ENABLED',type:'plain_text',text:'false'},{name:'AUTH_STATE',type:'durable_object_namespace',class_name:'AuthState'}],keep_bindings:['plain_text','json','secret_text','secret_key']});
test('command defaults refuse execution; only explicit future approval and pinned version accepted',()=>{assert.deepEqual(deploy.parse(['--dry-run']),{dryRun:true});const execute=['--execute','--account-id',ACCOUNT,'--expected-version',deploy.VERSION,'--approval','STAGE1-POSTS-OFF'];assert.equal(deploy.parse(execute).accountId,ACCOUNT);for(const args of [[],['deploy'],['--execute'],['--dry-run','--strict=false'],execute.map(x=>x===deploy.VERSION?'other':x),[...execute,'--secrets-file','test'],[...execute,'--execute']])assert.throws(()=>deploy.parse(args));});
test('fixed local config and mandatory CLI options preserve validation-only candidate',()=>{deploy.localConfig();const args=deploy.cliArgs(false);for(const value of ['--strict','--keep-vars','FORUM_POSTS_ENABLED:false'])assert.ok(args.includes(value));assert.equal(candidate.sha(fs.readFileSync(path.resolve(__dirname,'../tools/wrangler-strict-candidate.cjs'))),'9f3be8a818f7bafce7d4220399d492f6487a110750db7bdaba98a37c9940dd5a');});
test('GET-only snapshot checks account, latest/active version, namespace/backend, tag and all settings',async()=>{const f=fixture(),seen=[];const snapshot=await deploy.snapshot(async p=>{seen.push(p);return reader(f)(p);},ACCOUNT);assert.equal(snapshot.namespaceId,deploy.NAMESPACE);assert.ok(seen.every(p=>p===root||p.startsWith(root+'/')));assert.ok(!seen.some(p=>/\/secrets(?:\/|$)|\/namespaces\/[^/?]+\/objects/.test(p)));});
test('identity and migration mismatches fail closed',async()=>{for(const alter of [f=>f[root].id='b'.repeat(32),f=>f[script+'/versions'].items[0].id='wrong',f=>f[script+'/deployments'].deployments[0].versions[0].percentage=50,f=>f[service].default_environment.environment='staging',f=>f[service+'/environments/production'].script.migration_tag='wrong',f=>f[service+'/environments/production/bindings'].at(-1).namespace_id='wrong',f=>f[root+'/workers/durable_objects/namespaces?page=1&per_page=100'][0].use_sqlite=false,f=>f[root+'/workers/durable_objects/namespaces?page=1&per_page=100'][0].script='other']){const f=fixture();alter(f);await assert.rejects(()=>deploy.snapshot(reader(f),ACCOUNT));}});
test('unknown settings, bindings, secret-value shape, flags, routes and schedules are rejected',async()=>{for(const alter of [f=>f[service+'/environments/production'].script.unknown_setting=true,f=>f[service+'/environments/production'].script.limits={cpu_ms:300000},f=>f[service+'/environments/production'].script.observability.enabled=true,f=>f[service+'/environments/production/bindings'].push({name:'OTHER',type:'plain_text',text:'TEST_ONLY'}),f=>f[service+'/environments/production/bindings'][0].text='TEST_ONLY',f=>f[service+'/environments/production/bindings'].pop(),f=>f[service+'/environments/production/subdomain'].previews_enabled=true,f=>f[service+'/environments/production/routes?show_zonename=true'].push({pattern:'other'}),f=>f[script+'/schedules'].schedules.push({cron:'* * * * *'})]){const f=fixture();alter(f);await assert.rejects(()=>deploy.snapshot(reader(f),ACCOUNT));}});
test('concurrent version/deployment change during reads is rejected',async()=>{let calls=0;const f=fixture();await assert.rejects(()=>deploy.snapshot(async p=>{const value=await reader(f)(p);if(p===script+'/deployments'&&++calls===2)value.deployments[0].id='changed';return value;},ACCOUNT));});
test('GET failures never proceed to upload',async()=>{let writes=0;const api={stage1Read:async()=>{throw new Error('TEST_ONLY');},stage1Write:async()=>{writes++;}};const h=deploy.hooks(api,{accountId:ACCOUNT,dryRun:false});await assert.rejects(()=>h.preflight({name:deploy.WORKER,accountId:ACCOUNT,keepVars:true,strict:true},{}));assert.equal(writes,0);});
test('write guard rechecks immediately before mock POST and prohibits migration and altered metadata',async()=>{let writes=0;const api={stage1Read:async(_c,p)=>reader(fixture())(p),stage1Write:async()=>{writes++;return {id:'MOCK_NEW_VERSION'};}};const h=deploy.hooks(api,{accountId:ACCOUNT,dryRun:false}),resource=script+'/versions';const init={method:'POST',body:{get:()=>JSON.stringify(metadata())}};await h.upload({},resource,init);assert.equal(writes,1);for(const change of [m=>m.migrations={new_tag:'wrong'},m=>m.bindings[1].class_name='OTHER',m=>m.bindings[0].text='true',m=>m.keep_bindings=[]]){const m=metadata();change(m);await assert.rejects(()=>h.upload({},resource,{...init,body:{get:()=>JSON.stringify(m)}}));}await assert.rejects(()=>h.upload({},'/other',init));assert.equal(writes,1);assert.throws(()=>deploy.assertNoMigration({}));deploy.assertNoMigration(undefined);});
test('dry-run hooks cannot write even with valid mocked remote state',async()=>{let writes=0;const h=deploy.hooks({stage1Write:async()=>writes++},{dryRun:true});await assert.rejects(()=>h.upload({},script+'/versions',{method:'POST'}));assert.equal(writes,0);});
test('only intentional false flag addition is permitted; unknown additive differences are rejected',()=>{assert.equal(deploy.allowedDiff(null),true);assert.equal(deploy.allowedDiff({vars:{FORUM_POSTS_ENABLED__added:'false'}}),true);for(const d of [{vars:{OTHER__added:'x'}},{durable_objects:{bindings:[['+',{}]]}},{vars:{FORUM_POSTS_ENABLED__added:'true'}}])assert.equal(deploy.allowedDiff(d),false);});
test('actual patched Wrangler comparison rejects real changes, additions and keeps original upload builder',()=>{const {source}=candidate.original(),patched=deploy.patchProduction(source);const api=candidate.load(patched,deploy.BRIDGE+'\ninit_config_diffs();init_map_worker_metadata_bindings();exports.auditDiff=getRemoteConfigDiff;exports.auditMap=mapWorkerMetadataBindings;');api.stage1Install({allowedDiff:deploy.allowedDiff,noMigration:deploy.assertNoMigration,preflight:async()=>{},upload:async()=>{}});const l={durable_objects:{bindings:[{name:'AUTH_STATE',class_name:'AuthState'}]},observability:{enabled:false}},r={name:'AUTH_STATE',class_name:'AuthState',type:'durable_object_namespace'};assert.equal(api.auditDiff(api.auditMap([r]),l).diff,null);assert.equal(api.auditDiff(api.auditMap([{...r,class_name:'wrong'}]),l).nonDestructive,false);assert.equal(api.auditDiff({...api.auditMap([r]),vars:{OTHER:'x'}},l).nonDestructive,false);const slice=s=>s.slice(s.indexOf('function createWorkerUploadForm('),s.indexOf('var init_create_worker_upload_form ='));assert.equal(slice(source),slice(patched));});
test('read-only preflight arguments cannot request execution and nested unexpected defaults fail closed',async()=>{assert.equal(deploy.parse(['--preflight','--account-id',ACCOUNT,'--expected-version',deploy.VERSION]).preflight,true);assert.throws(()=>deploy.parse(['--preflight','--execute','--account-id',ACCOUNT,'--expected-version',deploy.VERSION]));for(const value of [{enabled:false,logs:{enabled:true}},{enabled:false,unknown_setting:false}]){const f=fixture();f[service+'/environments/production'].script.observability=value;await assert.rejects(()=>deploy.snapshot(reader(f),ACCOUNT));}});
test('patched actual migration generator rejects pending migrations while matching auth-v1 is retained',async()=>{const {source}=candidate.original();const api=candidate.load(deploy.patchProduction(source),deploy.BRIDGE+`\ninit_durable();exports.auditMigration=async(tag)=>{const prior=fetchResult;fetchResult=async()=>({default_environment:{script:{migration_tag:tag}}});try{return await getMigrationsToUpload('discord-event-poster-api',{accountId:'TEST',config:{migrations:[{tag:'auth-v1',new_sqlite_classes:['AuthState']}]}});}finally{fetchResult=prior;}};`);api.stage1Install({allowedDiff:deploy.allowedDiff,noMigration:deploy.assertNoMigration,preflight:async()=>{},upload:async()=>{}});assert.equal(await api.auditMigration('auth-v1'),undefined);await assert.rejects(()=>api.auditMigration(undefined),/MIGRATION_FORBIDDEN/);});
test('real upload builder emits identical required-secret inherit metadata under production guard',()=>{const {source}=candidate.original();const expose='\ninit_create_worker_upload_form();init_secrets_validation();exports.form=createWorkerUploadForm;exports.inherit=addRequiredSecretsInheritBindings;';const original=candidate.load(source,expose),guarded=candidate.load(deploy.patchProduction(source),deploy.BRIDGE+expose);guarded.stage1Install({...deploy.hooks({}, {dryRun:true}),validateMetadata:deploy.assertUpload});const worker={main:{name:'index.js',type:'esm',content:'export default {}'},modules:[],compatibility_date:'2026-04-01',compatibility_flags:[],keepVars:true,keepSecrets:true,observability:{enabled:false}};const bindings={FORUM_POSTS_ENABLED:{type:'plain_text',value:'false'},AUTH_STATE:{type:'durable_object_namespace',class_name:'AuthState'}};original.inherit(deploy.localConfig(),bindings,{type:'deploy',workerExists:true});const a=original.form(worker,bindings,{dryRun:true}).get('metadata'),b=guarded.form(worker,bindings,{dryRun:true}).get('metadata');assert.equal(a,b);assert.equal(JSON.parse(b).bindings.filter(x=>x.type==='inherit').length,5);for(const mutate of [m=>m.limits={cpu_ms:300000},m=>m.bindings.at(-1).class_name='OTHER',m=>m.bindings[5].text='true',m=>m.bindings[0].type='secret_text']){const m=JSON.parse(b);mutate(m);assert.throws(()=>deploy.assertUpload(m));}});
